// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TM.Api.Data;

#nullable disable

namespace TM.Api.Data.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20241208025719_RecreateDepartment")]
    partial class RecreateDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TM.Api.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessCode = "PHY123",
                            Name = "Physics Dept",
                            Subject = "Physics"
                        },
                        new
                        {
                            Id = 2,
                            AccessCode = "HIS123",
                            Name = "History Dept",
                            Subject = "History"
                        },
                        new
                        {
                            Id = 3,
                            AccessCode = "MTH123",
                            Name = "Maths Dept",
                            Subject = "Maths"
                        });
                });

            modelBuilder.Entity("TM.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "university@email.com",
                            IsApproved = true,
                            Name = "University Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEKhLuoL79I/4lQIz+W3Jx+wepB/poTxihlOcD9MFg0d5uf+wqPsbUlrN8UPJC8Fyvg==",
                            Phone = "1234567890",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager@email.com",
                            IsApproved = true,
                            Name = "University Manager",
                            PasswordHash = "AQAAAAIAAYagAAAAEIaTBKjdxH//H2aJNoPubiECMc2qml3Q3uEhl/gn9xiXb16k7EFWYcwmioqrNZLEpA==",
                            Phone = "0987654321",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "department@email.com",
                            IsApproved = true,
                            Name = "Department Head",
                            PasswordHash = "AQAAAAIAAYagAAAAEIKQ7SXZXEYFiJbOAFb+Jma6nh7TyoFOj0ZG6FxYsLcCvA5Z4bWRs9kB0sGSs5mPVw==",
                            Phone = "1122334455",
                            Role = "Department"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
