// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TM.Api.Data;

#nullable disable

namespace TM.Api.Data.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20241207161237_AddDepartmentTable")]
    partial class AddDepartmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TM.Api.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TM.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "university@email.com",
                            IsApproved = true,
                            Name = "University Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEKeJWRlpOkv4jRIdVW84j3Hkc1uWdF7kWVLaihou5J4BiG4yZSbfjEG3Qt8UW2oODg==",
                            Phone = "1234567890",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager@email.com",
                            IsApproved = true,
                            Name = "University Manager",
                            PasswordHash = "AQAAAAIAAYagAAAAEA9zqMZ3BdQLzL0iJm6OsnWF7mXiTGg245GPIG5WvIcYdhMqJpax2u2s2hh6LaqI3Q==",
                            Phone = "0987654321",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "department@email.com",
                            IsApproved = true,
                            Name = "Department Head",
                            PasswordHash = "AQAAAAIAAYagAAAAEEFF2wkkfSaH2oJTG5X6bmrXZjqGnNI8wBpi+ka6/VfQBpfNNoieu+MTX1+RWRoIyA==",
                            Phone = "1122334455",
                            Role = "Department"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
