// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TM.Api.Data;

#nullable disable

namespace TM.Api.Data.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20241208045508_AddClassTable")]
    partial class AddClassTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TM.Api.Data.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Quantum Mechanics"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Thermodynamics"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Name = "World History"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            Name = "Linear Algebra"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Name = "Calculus"
                        });
                });

            modelBuilder.Entity("TM.Api.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessCode = "PHY123",
                            Name = "Physics Dept",
                            Subject = "Physics"
                        },
                        new
                        {
                            Id = 2,
                            AccessCode = "HIS123",
                            Name = "History Dept",
                            Subject = "History"
                        },
                        new
                        {
                            Id = 3,
                            AccessCode = "MTH123",
                            Name = "Maths Dept",
                            Subject = "Maths"
                        });
                });

            modelBuilder.Entity("TM.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "university@email.com",
                            IsApproved = true,
                            Name = "University Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEBud0pL7zbxiEio8WcEgTfNiLbL/eOlTybiFAQI1zH0V9P7Vn4PXaTFX9QoEgnLZ8w==",
                            Phone = "1234567890",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager@email.com",
                            IsApproved = true,
                            Name = "University Manager",
                            PasswordHash = "AQAAAAIAAYagAAAAEMEThdurJXWclfBW0stGBYs8QDcFj1pkDlltphucVhu5W1meGqnp8y3VYoEp4gB2Qw==",
                            Phone = "0987654321",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "department@email.com",
                            IsApproved = true,
                            Name = "Department Head",
                            PasswordHash = "AQAAAAIAAYagAAAAENX+JeU0G86rNyl0vK984fFWgMLjBEyjjcg4RKQoIIRC1hY5VyZNMOm7+/0+y2nsVg==",
                            Phone = "1122334455",
                            Role = "Department"
                        });
                });

            modelBuilder.Entity("TM.Api.Data.Entities.Class", b =>
                {
                    b.HasOne("TM.Api.Data.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
