// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TM.Api.Data;

#nullable disable

namespace TM.Api.Data.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20241207140319_SeedUserRolesInDB")]
    partial class SeedUserRolesInDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TM.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "university@email.com",
                            IsApproved = true,
                            Name = "University Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEF0QXFy+JV1ZlBXeNB6/8m/Dd4xf3NOPZBmIhMSNC1v9V+vsiPztqJ4mxQOuE2HE6A==",
                            Phone = "1234567890",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager@email.com",
                            IsApproved = true,
                            Name = "University Manager",
                            PasswordHash = "AQAAAAIAAYagAAAAEEDYOoVvwf45HR/H+C85nXNfBlQdsqtY0MQf52HXr1YUkoeJu611VPKELzHipmBkqg==",
                            Phone = "0987654321",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "department@email.com",
                            IsApproved = true,
                            Name = "Department Head",
                            PasswordHash = "AQAAAAIAAYagAAAAENDV/KgoRm25OQWZejYtOithYs4f47xV1PSXmCXrNvNrUrxPx47rec3SL6Bpmj0vGw==",
                            Phone = "1122334455",
                            Role = "Department"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
